//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave Pro is a high-performance backup solution designed to secure your data with XOR encryption and detailed real-time monitoring..
        /// </summary>
        public static string About_Intro {
            get {
                return ResourceManager.GetString("About_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully. .
        /// </summary>
        public static string Backup_Success {
            get {
                return ResourceManager.GetString("Backup_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup stopped by user..
        /// </summary>
        public static string Error_BackupStoppedByUser {
            get {
                return ResourceManager.GetString("Error_BackupStoppedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type not supported: {0}.
        /// </summary>
        public static string Error_BackupTypeNotSupported {
            get {
                return ResourceManager.GetString("Error_BackupTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.
        /// </summary>
        public static string Error_EmptyValue {
            get {
                return ResourceManager.GetString("Error_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        /// </summary>
        public static string Error_InvalidChoice {
            get {
                return ResourceManager.GetString("Error_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number.
        /// </summary>
        public static string Error_InvalidNumber {
            get {
                return ResourceManager.GetString("Error_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs found..
        /// </summary>
        public static string Error_JobNotFound {
            get {
                return ResourceManager.GetString("Error_JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERREUR] The source folder does not exist : {0}.
        /// </summary>
        public static string Error_SourceFolderMissing {
            get {
                return ResourceManager.GetString("Error_SourceFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OK] {0} copied in {1} ms.
        /// </summary>
        public static string FileCopied {
            get {
                return ResourceManager.GetString("FileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Project on GitHub.
        /// </summary>
        public static string GitHub_Button {
            get {
                return ResourceManager.GetString("GitHub_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub :.
        /// </summary>
        public static string Gui_About_GitHubLabel {
            get {
                return ResourceManager.GetString("Gui_About_GitHubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Manager Pro.
        /// </summary>
        public static string Gui_App_Tagline {
            get {
                return ResourceManager.GetString("Gui_App_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Gui_Common_Active {
            get {
                return ResourceManager.GetString("Gui_Common_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Gui_Common_Backup {
            get {
                return ResourceManager.GetString("Gui_Common_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Gui_Common_Browse {
            get {
                return ResourceManager.GetString("Gui_Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Gui_Common_Cancel {
            get {
                return ResourceManager.GetString("Gui_Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string Gui_Common_Differential {
            get {
                return ResourceManager.GetString("Gui_Common_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Gui_Common_Full {
            get {
                return ResourceManager.GetString("Gui_Common_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Gui_Common_Inactive {
            get {
                return ResourceManager.GetString("Gui_Common_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Gui_Common_Never {
            get {
                return ResourceManager.GetString("Gui_Common_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Gui_Common_NotAvailable {
            get {
                return ResourceManager.GetString("Gui_Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Gui_Common_Unknown {
            get {
                return ResourceManager.GetString("Gui_Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to run.
        /// </summary>
        public static string Gui_Dashboard_Active_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Active_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string Gui_Dashboard_Active_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Active_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup activity.
        /// </summary>
        public static string Gui_Dashboard_Activity_Backup {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Activity_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Gui_Dashboard_Activity_Job {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Activity_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential backup.
        /// </summary>
        public static string Gui_Dashboard_Backup_Differential {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full backup.
        /// </summary>
        public static string Gui_Dashboard_Backup_Full {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Gui_Dashboard_Backup_Generic {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory created | {0}.
        /// </summary>
        public static string Gui_Dashboard_DirectoryCreated_Format {
            get {
                return ResourceManager.GetString("Gui_Dashboard_DirectoryCreated_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error | {0}.
        /// </summary>
        public static string Gui_Dashboard_Error_Format {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copy.
        /// </summary>
        public static string Gui_Dashboard_FileCopy {
            get {
                return ResourceManager.GetString("Gui_Dashboard_FileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs deactivated (not runnable).
        /// </summary>
        public static string Gui_Dashboard_Inactive_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Inactive_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVE.
        /// </summary>
        public static string Gui_Dashboard_Inactive_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Inactive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job changed.
        /// </summary>
        public static string Gui_Dashboard_Job_Changed {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job created.
        /// </summary>
        public static string Gui_Dashboard_Job_Created {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job deleted.
        /// </summary>
        public static string Gui_Dashboard_Job_Deleted {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job paused.
        /// </summary>
        public static string Gui_Dashboard_Job_Paused {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job resumed.
        /// </summary>
        public static string Gui_Dashboard_Job_Resumed {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Resumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job stopped.
        /// </summary>
        public static string Gui_Dashboard_Job_Stopped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job updated.
        /// </summary>
        public static string Gui_Dashboard_Job_Updated {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a backup to see the latest events.
        /// </summary>
        public static string Gui_Dashboard_Recent_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Empty_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent activity yet.
        /// </summary>
        public static string Gui_Dashboard_Recent_Empty_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string Gui_Dashboard_Recent_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string Gui_Dashboard_Settings_Saved {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Gui_Dashboard_Settings_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated.
        /// </summary>
        public static string Gui_Dashboard_Settings_Updated {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string Gui_Dashboard_Skipped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0}.
        /// </summary>
        public static string Gui_Dashboard_Summary_Copied {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors {0}.
        /// </summary>
        public static string Gui_Dashboard_Summary_Errors {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped {0}.
        /// </summary>
        public static string Gui_Dashboard_Summary_Skipped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transferred.
        /// </summary>
        public static string Gui_Dashboard_Summary_Transferred {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Transferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured backups.
        /// </summary>
        public static string Gui_Dashboard_TotalJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_TotalJobs_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL JOBS.
        /// </summary>
        public static string Gui_Dashboard_TotalJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_TotalJobs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done: {0} bytes.
        /// </summary>
        public static string Gui_Execution_BytesDoneFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesDoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining: {0} bytes.
        /// </summary>
        public static string Gui_Execution_BytesRemainingFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesRemainingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} bytes.
        /// </summary>
        public static string Gui_Execution_BytesTotalFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software is running. Cannot start sequence..
        /// </summary>
        public static string Gui_Execution_Error_BusinessSoftware {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_BusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runnable jobs..
        /// </summary>
        public static string Gui_Execution_Error_NoRunnable {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_NoRunnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job with ID {0} not found..
        /// </summary>
        public static string Gui_Execution_Error_NotFound {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to pause job..
        /// </summary>
        public static string Gui_Execution_Error_Pause {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resume job..
        /// </summary>
        public static string Gui_Execution_Error_Resume {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop job..
        /// </summary>
        public static string Gui_Execution_Error_Stop {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Gui_Execution_ErrorFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}.
        /// </summary>
        public static string Gui_Execution_FilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_FilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last action: {0}.
        /// </summary>
        public static string Gui_Execution_LastActionFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_LastActionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup job to start monitoring.
        /// </summary>
        public static string Gui_Execution_NoJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Execution_NoJobs_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs.
        /// </summary>
        public static string Gui_Execution_NoJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Execution_NoJobs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Gui_Execution_Pause {
            get {
                return ResourceManager.GetString("Gui_Execution_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Gui_Execution_Play {
            get {
                return ResourceManager.GetString("Gui_Execution_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0}.
        /// </summary>
        public static string Gui_Execution_ProgressFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining: {0}.
        /// </summary>
        public static string Gui_Execution_RemainingFilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_RemainingFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Gui_Execution_Resume {
            get {
                return ResourceManager.GetString("Gui_Execution_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All.
        /// </summary>
        public static string Gui_Execution_RunAll {
            get {
                return ResourceManager.GetString("Gui_Execution_RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: -.
        /// </summary>
        public static string Gui_Execution_SourceEmpty {
            get {
                return ResourceManager.GetString("Gui_Execution_SourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: {0}.
        /// </summary>
        public static string Gui_Execution_SourceFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_SourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: -.
        /// </summary>
        public static string Gui_Execution_TargetEmpty {
            get {
                return ResourceManager.GetString("Gui_Execution_TargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        public static string Gui_Execution_TargetFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TargetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string Gui_Execution_TotalFilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TotalFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string Gui_Execution_TypeFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Job.
        /// </summary>
        public static string Gui_JobEditor_ActiveJob {
            get {
                return ResourceManager.GetString("Gui_JobEditor_ActiveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active jobs can be executed.
        /// </summary>
        public static string Gui_JobEditor_ActiveJob_Hint {
            get {
                return ResourceManager.GetString("Gui_JobEditor_ActiveJob_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete: backs up all files | Differential: backs up only modified files.
        /// </summary>
        public static string Gui_JobEditor_BackupTypeHelp {
            get {
                return ResourceManager.GetString("Gui_JobEditor_BackupTypeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Type *.
        /// </summary>
        public static string Gui_JobEditor_BackupTypeLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_BackupTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        public static string Gui_JobEditor_CreateButton {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: {0:dd/MM/yyyy HH:mm}.
        /// </summary>
        public static string Gui_JobEditor_CreatedFormat {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a new backup job.
        /// </summary>
        public static string Gui_JobEditor_CreateSubtitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job.
        /// </summary>
        public static string Gui_JobEditor_CreateTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the backup job settings.
        /// </summary>
        public static string Gui_JobEditor_EditSubtitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_EditSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job.
        /// </summary>
        public static string Gui_JobEditor_EditTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be under {0} characters..
        /// </summary>
        public static string Gui_JobEditor_Error_NameLength {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string Gui_JobEditor_Error_NameRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path is required..
        /// </summary>
        public static string Gui_JobEditor_Error_SourceRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_SourceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path is required..
        /// </summary>
        public static string Gui_JobEditor_Error_TargetRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_TargetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Information.
        /// </summary>
        public static string Gui_JobEditor_InfoTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run: {0:dd/MM/yyyy HH:mm}.
        /// </summary>
        public static string Gui_JobEditor_LastRunFormat {
            get {
                return ResourceManager.GetString("Gui_JobEditor_LastRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run: Never.
        /// </summary>
        public static string Gui_JobEditor_LastRunNever {
            get {
                return ResourceManager.GetString("Gui_JobEditor_LastRunNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name *.
        /// </summary>
        public static string Gui_JobEditor_NameLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Documents Backup.
        /// </summary>
        public static string Gui_JobEditor_NameWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_NameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required fields.
        /// </summary>
        public static string Gui_JobEditor_RequiredFields {
            get {
                return ResourceManager.GetString("Gui_JobEditor_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Gui_JobEditor_SaveChanges {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Path *.
        /// </summary>
        public static string Gui_JobEditor_SourceLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Users\\Documents.
        /// </summary>
        public static string Gui_JobEditor_SourceWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SourceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Path *.
        /// </summary>
        public static string Gui_JobEditor_TargetLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_TargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\\Backups\\Documents.
        /// </summary>
        public static string Gui_JobEditor_TargetWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_TargetWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Gui_Jobs_Active {
            get {
                return ResourceManager.GetString("Gui_Jobs_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} active job(s).
        /// </summary>
        public static string Gui_Jobs_ActiveJobsFormat {
            get {
                return ResourceManager.GetString("Gui_Jobs_ActiveJobsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create First Job.
        /// </summary>
        public static string Gui_Jobs_CreateFirst {
            get {
                return ResourceManager.GetString("Gui_Jobs_CreateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Gui_Jobs_Delete {
            get {
                return ResourceManager.GetString("Gui_Jobs_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        public static string Gui_Jobs_DeleteTooltip {
            get {
                return ResourceManager.GetString("Gui_Jobs_DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Gui_Jobs_Edit {
            get {
                return ResourceManager.GetString("Gui_Jobs_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit job.
        /// </summary>
        public static string Gui_Jobs_EditTooltip {
            get {
                return ResourceManager.GetString("Gui_Jobs_EditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Gui_Jobs_Inactive {
            get {
                return ResourceManager.GetString("Gui_Jobs_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Gui_Jobs_Label_Source {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:.
        /// </summary>
        public static string Gui_Jobs_Label_Target {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Gui_Jobs_Label_Type {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run: {0:dd/MM/yyyy HH:mm}.
        /// </summary>
        public static string Gui_Jobs_LastRunFormat {
            get {
                return ResourceManager.GetString("Gui_Jobs_LastRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never executed.
        /// </summary>
        public static string Gui_Jobs_LastRunNever {
            get {
                return ResourceManager.GetString("Gui_Jobs_LastRunNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + New Job.
        /// </summary>
        public static string Gui_Jobs_New {
            get {
                return ResourceManager.GetString("Gui_Jobs_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first backup job to get started.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Hint {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup jobs yet.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Gui_JobStatus_Completed {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Gui_JobStatus_Error {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Gui_JobStatus_Idle {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Gui_JobStatus_Paused {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Gui_JobStatus_Running {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string Gui_LogFormat_Json {
            get {
                return ResourceManager.GetString("Gui_LogFormat_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string Gui_LogFormat_Xml {
            get {
                return ResourceManager.GetString("Gui_LogFormat_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Gui_Nav_About {
            get {
                return ResourceManager.GetString("Gui_Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Jobs.
        /// </summary>
        public static string Gui_Nav_BackupJobs {
            get {
                return ResourceManager.GetString("Gui_Nav_BackupJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Gui_Nav_Dashboard {
            get {
                return ResourceManager.GetString("Gui_Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Execution.
        /// </summary>
        public static string Gui_Nav_LiveExecution {
            get {
                return ResourceManager.GetString("Gui_Nav_LiveExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Gui_Nav_Logs {
            get {
                return ResourceManager.GetString("Gui_Nav_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Gui_Nav_Settings {
            get {
                return ResourceManager.GetString("Gui_Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business software process name (e.g., CalculatorApp):.
        /// </summary>
        public static string Gui_Settings_BusinessProcessLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name used to block backups when running.
        /// </summary>
        public static string Gui_Settings_BusinessProcessTooltip {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty to disable.
        /// </summary>
        public static string Gui_Settings_BusinessProcessWatermark {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XOR encryption.
        /// </summary>
        public static string Gui_Settings_EnableXor {
            get {
                return ResourceManager.GetString("Gui_Settings_EnableXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions to encrypt (e.g., .pdf, .txt):.
        /// </summary>
        public static string Gui_Settings_ExtensionsLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Separate extensions with a comma..
        /// </summary>
        public static string Gui_Settings_ExtensionsNote {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with these extensions will be encrypted.
        /// </summary>
        public static string Gui_Settings_ExtensionsTooltip {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma-separated extensions....
        /// </summary>
        public static string Gui_Settings_ExtensionsWatermark {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure global application settings.
        /// </summary>
        public static string Gui_Settings_Info {
            get {
                return ResourceManager.GetString("Gui_Settings_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Gui_Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format:.
        /// </summary>
        public static string Gui_Settings_LogFormatLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_LogFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key:.
        /// </summary>
        public static string Gui_Settings_SecretKeyLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_SecretKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Gui_Settings_Title {
            get {
                return ResourceManager.GetString("Gui_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        public static string Gui_Sidebar_System {
            get {
                return ResourceManager.GetString("Gui_Sidebar_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKSPACE.
        /// </summary>
        public static string Gui_Sidebar_Workspace {
            get {
                return ResourceManager.GetString("Gui_Sidebar_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application information.
        /// </summary>
        public static string Gui_Status_AboutInfo {
            get {
                return ResourceManager.GetString("Gui_Status_AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string Gui_Status_JobFormat {
            get {
                return ResourceManager.GetString("Gui_Status_JobFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time backup monitoring.
        /// </summary>
        public static string Gui_Status_LiveMonitoring {
            get {
                return ResourceManager.GetString("Gui_Status_LiveMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your backup jobs.
        /// </summary>
        public static string Gui_Status_ManageJobs {
            get {
                return ResourceManager.GetString("Gui_Status_ManageJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of all backup operations.
        /// </summary>
        public static string Gui_Status_Overview {
            get {
                return ResourceManager.GetString("Gui_Status_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Gui_Status_Ready {
            get {
                return ResourceManager.GetString("Gui_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application settings.
        /// </summary>
        public static string Gui_Status_SettingsInfo {
            get {
                return ResourceManager.GetString("Gui_Status_SettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View execution logs.
        /// </summary>
        public static string Gui_Status_ViewLogs {
            get {
                return ResourceManager.GetString("Gui_Status_ViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILED USER GUIDE.
        /// </summary>
        public static string Guide_Title {
            get {
                return ResourceManager.GetString("Guide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed with errors..
        /// </summary>
        public static string Info_BackupCompletedWithErrors {
            get {
                return ResourceManager.GetString("Info_BackupCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language updated.
        /// </summary>
        public static string Info_LanguageChanged {
            get {
                return ResourceManager.GetString("Info_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format updated.
        /// </summary>
        public static string Info_LogFormatChanged {
            get {
                return ResourceManager.GetString("Info_LogFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage backup job.
        /// </summary>
        public static string Menu_Create {
            get {
                return ResourceManager.GetString("Menu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run backup job.
        /// </summary>
        public static string Menu_Run {
            get {
                return ResourceManager.GetString("Menu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to &apos;Backup Jobs&apos;. Click the add button to define a new task. 
        ///You must provide a unique name, a valid source directory, and a target destination. 
        ///Choose between &apos;Full&apos; (complete copy) or &apos;Differential&apos; (only changed files)..
        /// </summary>
        public static string Step1_Desc {
            get {
                return ResourceManager.GetString("Step1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Backup Job Configuration.
        /// </summary>
        public static string Step1_Title {
            get {
                return ResourceManager.GetString("Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &apos;Settings&apos;, define your secret XOR key. 
        ///Use the &apos;Extensions to encrypt&apos; section to add specific formats (e.g., .txt, .docx). 
        ///Only files with these extensions will be encrypted during the backup process..
        /// </summary>
        public static string Step2_Desc {
            get {
                return ResourceManager.GetString("Step2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Security &amp; Encryption Whitelist.
        /// </summary>
        public static string Step2_Title {
            get {
                return ResourceManager.GetString("Step2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to &apos;Live Execution&apos; to start your jobs. You can monitor progress bars in real-time. 
        /// All actions are recorded in the &apos;Logs&apos; folder (JSON or XML format) for auditing and error tracking..
        /// </summary>
        public static string Step3_Desc {
            get {
                return ResourceManager.GetString("Step3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Execution &amp; Logs.
        /// </summary>
        public static string Step3_Title {
            get {
                return ResourceManager.GetString("Step3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPMENT TEAM.
        /// </summary>
        public static string Team_Title {
            get {
                return ResourceManager.GetString("Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string UI_BackupTitle {
            get {
                return ResourceManager.GetString("UI_BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string UI_BackupTypeDifferential {
            get {
                return ResourceManager.GetString("UI_BackupTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string UI_BackupTypeFull {
            get {
                return ResourceManager.GetString("UI_BackupTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type.
        /// </summary>
        public static string UI_BackupTypePrompt {
            get {
                return ResourceManager.GetString("UI_BackupTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: {0} / {1}.
        /// </summary>
        public static string UI_BatchSuccess {
            get {
                return ResourceManager.GetString("UI_BatchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch summary.
        /// </summary>
        public static string UI_BatchSummary {
            get {
                return ResourceManager.GetString("UI_BatchSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create job.
        /// </summary>
        public static string UI_CreateJob {
            get {
                return ResourceManager.GetString("UI_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job.
        /// </summary>
        public static string UI_DeleteJob {
            get {
                return ResourceManager.GetString("UI_DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job id: .
        /// </summary>
        public static string UI_JobIdPrompt {
            get {
                return ResourceManager.GetString("UI_JobIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name: .
        /// </summary>
        public static string UI_JobNamePrompt {
            get {
                return ResourceManager.GetString("UI_JobNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string UI_JobsTitle {
            get {
                return ResourceManager.GetString("UI_JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List jobs.
        /// </summary>
        public static string UI_ListJobs {
            get {
                return ResourceManager.GetString("UI_ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format: JSON.
        /// </summary>
        public static string UI_LogFormatJson {
            get {
                return ResourceManager.GetString("UI_LogFormatJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format: XML.
        /// </summary>
        public static string UI_LogFormatXml {
            get {
                return ResourceManager.GetString("UI_LogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs configured..
        /// </summary>
        public static string UI_NoJobsConfigured {
            get {
                return ResourceManager.GetString("UI_NoJobsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs executed..
        /// </summary>
        public static string UI_NoJobsExecuted {
            get {
                return ResourceManager.GetString("UI_NoJobsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        public static string UI_PressKey {
            get {
                return ResourceManager.GetString("UI_PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: {0} - {1}.
        /// </summary>
        public static string UI_Result {
            get {
                return ResourceManager.GetString("UI_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string UI_ResultFailed {
            get {
                return ResourceManager.GetString("UI_ResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UI_ResultSuccess {
            get {
                return ResourceManager.GetString("UI_ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all jobs.
        /// </summary>
        public static string UI_RunAllJobs {
            get {
                return ResourceManager.GetString("UI_RunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run one job.
        /// </summary>
        public static string UI_RunOneJob {
            get {
                return ResourceManager.GetString("UI_RunOneJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running job {0} - {1}.
        /// </summary>
        public static string UI_RunStart {
            get {
                return ResourceManager.GetString("UI_RunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path: .
        /// </summary>
        public static string UI_SourcePathPrompt {
            get {
                return ResourceManager.GetString("UI_SourcePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path: .
        /// </summary>
        public static string UI_TargetPathPrompt {
            get {
                return ResourceManager.GetString("UI_TargetPathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update job.
        /// </summary>
        public static string UI_UpdateJob {
            get {
                return ResourceManager.GetString("UI_UpdateJob", resourceCulture);
            }
        }
    }
}
