//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully. .
        /// </summary>
        public static string Backup_Success {
            get {
                return ResourceManager.GetString("Backup_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.
        ///   Recherche une chaîne localisée semblable à Value cannot be empty.
        /// </summary>
        public static string Error_EmptyValue {
            get {
                return ResourceManager.GetString("Error_EmptyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup type not supported: {0}.
        /// </summary>
        public static string Error_BackupTypeNotSupported {
            get {
                return ResourceManager.GetString("Error_BackupTypeNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup stopped by user..
        /// </summary>
        public static string Error_BackupStoppedByUser {
            get {
                return ResourceManager.GetString("Error_BackupStoppedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        ///   Recherche une chaîne localisée semblable à Invalid choice.
        /// </summary>
        public static string Error_InvalidChoice {
            get {
                return ResourceManager.GetString("Error_InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid number.
        /// </summary>
        public static string Error_InvalidNumber {
            get {
                return ResourceManager.GetString("Error_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs found..
        /// </summary>
        public static string Error_JobNotFound {
            get {
                return ResourceManager.GetString("Error_JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERREUR] The source folder does not exist : {0}.
        /// </summary>
        public static string Error_SourceFolderMissing {
            get {
                return ResourceManager.GetString("Error_SourceFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OK] {0} copied in {1} ms.
        /// </summary>
        public static string FileCopied {
            get {
                return ResourceManager.GetString("FileCopied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup completed with errors..
        /// </summary>
        public static string Info_BackupCompletedWithErrors {
            get {
                return ResourceManager.GetString("Info_BackupCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language updated.
        ///   Recherche une chaîne localisée semblable à Language updated.
        /// </summary>
        public static string Info_LanguageChanged {
            get {
                return ResourceManager.GetString("Info_LanguageChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log format updated.
        /// </summary>
        public static string Info_LogFormatChanged {
            get {
                return ResourceManager.GetString("Info_LogFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage backup job.
        /// </summary>
        public static string Menu_Create {
            get {
                return ResourceManager.GetString("Menu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run backup job.
        /// </summary>
        public static string Menu_Run {
            get {
                return ResourceManager.GetString("Menu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log format: JSON.
        /// </summary>
        public static string UI_LogFormatJson {
            get {
                return ResourceManager.GetString("UI_LogFormatJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log format: XML.
        /// </summary>
        public static string UI_LogFormatXml {
            get {
                return ResourceManager.GetString("UI_LogFormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup.
        /// </summary>
        public static string UI_BackupTitle {
            get {
                return ResourceManager.GetString("UI_BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string UI_BackupTypeDifferential {
            get {
                return ResourceManager.GetString("UI_BackupTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string UI_BackupTypeFull {
            get {
                return ResourceManager.GetString("UI_BackupTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type.
        /// </summary>
        public static string UI_BackupTypePrompt {
            get {
                return ResourceManager.GetString("UI_BackupTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: {0} / {1}.
        /// </summary>
        public static string UI_BatchSuccess {
            get {
                return ResourceManager.GetString("UI_BatchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch summary.
        /// </summary>
        public static string UI_BatchSummary {
            get {
                return ResourceManager.GetString("UI_BatchSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create job.
        /// </summary>
        public static string UI_CreateJob {
            get {
                return ResourceManager.GetString("UI_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job.
        /// </summary>
        public static string UI_DeleteJob {
            get {
                return ResourceManager.GetString("UI_DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job id: .
        /// </summary>
        public static string UI_JobIdPrompt {
            get {
                return ResourceManager.GetString("UI_JobIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name: .
        /// </summary>
        public static string UI_JobNamePrompt {
            get {
                return ResourceManager.GetString("UI_JobNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string UI_JobsTitle {
            get {
                return ResourceManager.GetString("UI_JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List jobs.
        /// </summary>
        public static string UI_ListJobs {
            get {
                return ResourceManager.GetString("UI_ListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No jobs configured..
        /// </summary>
        public static string UI_NoJobsConfigured {
            get {
                return ResourceManager.GetString("UI_NoJobsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No jobs executed..
        /// </summary>
        public static string UI_NoJobsExecuted {
            get {
                return ResourceManager.GetString("UI_NoJobsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue....
        /// </summary>
        public static string UI_PressKey {
            get {
                return ResourceManager.GetString("UI_PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result: {0} - {1}.
        /// </summary>
        public static string UI_Result {
            get {
                return ResourceManager.GetString("UI_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed.
        /// </summary>
        public static string UI_ResultFailed {
            get {
                return ResourceManager.GetString("UI_ResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string UI_ResultSuccess {
            get {
                return ResourceManager.GetString("UI_ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run all jobs.
        /// </summary>
        public static string UI_RunAllJobs {
            get {
                return ResourceManager.GetString("UI_RunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run one job.
        /// </summary>
        public static string UI_RunOneJob {
            get {
                return ResourceManager.GetString("UI_RunOneJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running job {0} - {1}.
        /// </summary>
        public static string UI_RunStart {
            get {
                return ResourceManager.GetString("UI_RunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source path: .
        /// </summary>
        public static string UI_SourcePathPrompt {
            get {
                return ResourceManager.GetString("UI_SourcePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target path: .
        /// </summary>
        public static string UI_TargetPathPrompt {
            get {
                return ResourceManager.GetString("UI_TargetPathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update job.
        /// </summary>
        public static string About_Intro {
            get {
                return ResourceManager.GetString("About_Intro", resourceCulture);
            }
        }
        
        public static string UI_UpdateJob {
            get {
                return ResourceManager.GetString("UI_UpdateJob", resourceCulture);
            }
        }
        
        public static string Guide_Title {
            get {
                return ResourceManager.GetString("Guide_Title", resourceCulture);
            }
        }
        
        public static string Step1_Title {
            get {
                return ResourceManager.GetString("Step1_Title", resourceCulture);
            }
        }
        
        public static string Step1_Desc {
            get {
                return ResourceManager.GetString("Step1_Desc", resourceCulture);
            }
        }
        
        public static string Step2_Title {
            get {
                return ResourceManager.GetString("Step2_Title", resourceCulture);
            }
        }
        
        public static string Step2_Desc {
            get {
                return ResourceManager.GetString("Step2_Desc", resourceCulture);
            }
        }
        
        public static string Step3_Title {
            get {
                return ResourceManager.GetString("Step3_Title", resourceCulture);
            }
        }
        
        public static string Step3_Desc {
            get {
                return ResourceManager.GetString("Step3_Desc", resourceCulture);
            }
        }
        
        public static string Team_Title {
            get {
                return ResourceManager.GetString("Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub_Button.
        /// </summary>
        public static string GitHub_Button {
            get {
                return ResourceManager.GetString("GitHub_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_About_GitHubLabel.
        /// </summary>
        public static string Gui_About_GitHubLabel {
            get {
                return ResourceManager.GetString("Gui_About_GitHubLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_App_Tagline.
        /// </summary>
        public static string Gui_App_Tagline {
            get {
                return ResourceManager.GetString("Gui_App_Tagline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Active.
        /// </summary>
        public static string Gui_Common_Active {
            get {
                return ResourceManager.GetString("Gui_Common_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Backup.
        /// </summary>
        public static string Gui_Common_Backup {
            get {
                return ResourceManager.GetString("Gui_Common_Backup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Browse.
        /// </summary>
        public static string Gui_Common_Browse {
            get {
                return ResourceManager.GetString("Gui_Common_Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Cancel.
        /// </summary>
        public static string Gui_Common_Cancel {
            get {
                return ResourceManager.GetString("Gui_Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Differential.
        /// </summary>
        public static string Gui_Common_Differential {
            get {
                return ResourceManager.GetString("Gui_Common_Differential", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Full.
        /// </summary>
        public static string Gui_Common_Full {
            get {
                return ResourceManager.GetString("Gui_Common_Full", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Inactive.
        /// </summary>
        public static string Gui_Common_Inactive {
            get {
                return ResourceManager.GetString("Gui_Common_Inactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Never.
        /// </summary>
        public static string Gui_Common_Never {
            get {
                return ResourceManager.GetString("Gui_Common_Never", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_NotAvailable.
        /// </summary>
        public static string Gui_Common_NotAvailable {
            get {
                return ResourceManager.GetString("Gui_Common_NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Common_Unknown.
        /// </summary>
        public static string Gui_Common_Unknown {
            get {
                return ResourceManager.GetString("Gui_Common_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Active_Subtitle.
        /// </summary>
        public static string Gui_Dashboard_Active_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Active_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Active_Title.
        /// </summary>
        public static string Gui_Dashboard_Active_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Active_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Activity_Backup.
        /// </summary>
        public static string Gui_Dashboard_Activity_Backup {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Activity_Backup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Activity_Job.
        /// </summary>
        public static string Gui_Dashboard_Activity_Job {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Activity_Job", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Backup_Differential.
        /// </summary>
        public static string Gui_Dashboard_Backup_Differential {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Differential", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Backup_Full.
        /// </summary>
        public static string Gui_Dashboard_Backup_Full {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Full", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Backup_Generic.
        /// </summary>
        public static string Gui_Dashboard_Backup_Generic {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Backup_Generic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_DirectoryCreated_Format.
        /// </summary>
        public static string Gui_Dashboard_DirectoryCreated_Format {
            get {
                return ResourceManager.GetString("Gui_Dashboard_DirectoryCreated_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Error_Format.
        /// </summary>
        public static string Gui_Dashboard_Error_Format {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Error_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_FileCopy.
        /// </summary>
        public static string Gui_Dashboard_FileCopy {
            get {
                return ResourceManager.GetString("Gui_Dashboard_FileCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Inactive_Subtitle.
        /// </summary>
        public static string Gui_Dashboard_Inactive_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Inactive_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Inactive_Title.
        /// </summary>
        public static string Gui_Dashboard_Inactive_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Inactive_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Changed.
        /// </summary>
        public static string Gui_Dashboard_Job_Changed {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Changed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Created.
        /// </summary>
        public static string Gui_Dashboard_Job_Created {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Deleted.
        /// </summary>
        public static string Gui_Dashboard_Job_Deleted {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Updated.
        /// </summary>
        public static string Gui_Dashboard_Job_Updated {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Updated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Paused.
        /// </summary>
        public static string Gui_Dashboard_Job_Paused {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Resumed.
        /// </summary>
        public static string Gui_Dashboard_Job_Resumed {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Resumed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Job_Stopped.
        /// </summary>
        public static string Gui_Dashboard_Job_Stopped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Job_Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Recent_Empty_Subtitle.
        /// </summary>
        public static string Gui_Dashboard_Recent_Empty_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Empty_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Recent_Empty_Title.
        /// </summary>
        public static string Gui_Dashboard_Recent_Empty_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Empty_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Recent_Title.
        /// </summary>
        public static string Gui_Dashboard_Recent_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Recent_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Settings_Saved.
        /// </summary>
        public static string Gui_Dashboard_Settings_Saved {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Settings_Title.
        /// </summary>
        public static string Gui_Dashboard_Settings_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Settings_Updated.
        /// </summary>
        public static string Gui_Dashboard_Settings_Updated {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Settings_Updated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Skipped.
        /// </summary>
        public static string Gui_Dashboard_Skipped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Skipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Summary_Copied.
        /// </summary>
        public static string Gui_Dashboard_Summary_Copied {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Summary_Errors.
        /// </summary>
        public static string Gui_Dashboard_Summary_Errors {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Errors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Summary_Skipped.
        /// </summary>
        public static string Gui_Dashboard_Summary_Skipped {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Skipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_Summary_Transferred.
        /// </summary>
        public static string Gui_Dashboard_Summary_Transferred {
            get {
                return ResourceManager.GetString("Gui_Dashboard_Summary_Transferred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_TotalJobs_Subtitle.
        /// </summary>
        public static string Gui_Dashboard_TotalJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Dashboard_TotalJobs_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Dashboard_TotalJobs_Title.
        /// </summary>
        public static string Gui_Dashboard_TotalJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Dashboard_TotalJobs_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_BytesDoneFormat.
        /// </summary>
        public static string Gui_Execution_BytesDoneFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesDoneFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_BytesRemainingFormat.
        /// </summary>
        public static string Gui_Execution_BytesRemainingFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesRemainingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_BytesTotalFormat.
        /// </summary>
        public static string Gui_Execution_BytesTotalFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_BytesTotalFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_BusinessSoftware.
        /// </summary>
        public static string Gui_Execution_Error_BusinessSoftware {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_BusinessSoftware", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_NoRunnable.
        /// </summary>
        public static string Gui_Execution_Error_NoRunnable {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_NoRunnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_NotFound.
        /// </summary>
        public static string Gui_Execution_Error_NotFound {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_Pause.
        /// </summary>
        public static string Gui_Execution_Error_Pause {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_Resume.
        /// </summary>
        public static string Gui_Execution_Error_Resume {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Resume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Error_Stop.
        /// </summary>
        public static string Gui_Execution_Error_Stop {
            get {
                return ResourceManager.GetString("Gui_Execution_Error_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_ErrorFormat.
        /// </summary>
        public static string Gui_Execution_ErrorFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_ErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_FilesFormat.
        /// </summary>
        public static string Gui_Execution_FilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_FilesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_LastActionFormat.
        /// </summary>
        public static string Gui_Execution_LastActionFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_LastActionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_NoJobs_Subtitle.
        /// </summary>
        public static string Gui_Execution_NoJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Execution_NoJobs_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_NoJobs_Title.
        /// </summary>
        public static string Gui_Execution_NoJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Execution_NoJobs_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Pause.
        /// </summary>
        public static string Gui_Execution_Pause {
            get {
                return ResourceManager.GetString("Gui_Execution_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Play.
        /// </summary>
        public static string Gui_Execution_Play {
            get {
                return ResourceManager.GetString("Gui_Execution_Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_ProgressFormat.
        /// </summary>
        public static string Gui_Execution_ProgressFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_ProgressFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_RemainingFilesFormat.
        /// </summary>
        public static string Gui_Execution_RemainingFilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_RemainingFilesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_Resume.
        /// </summary>
        public static string Gui_Execution_Resume {
            get {
                return ResourceManager.GetString("Gui_Execution_Resume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_RunAll.
        /// </summary>
        public static string Gui_Execution_RunAll {
            get {
                return ResourceManager.GetString("Gui_Execution_RunAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_SourceEmpty.
        /// </summary>
        public static string Gui_Execution_SourceEmpty {
            get {
                return ResourceManager.GetString("Gui_Execution_SourceEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_SourceFormat.
        /// </summary>
        public static string Gui_Execution_SourceFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_SourceFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_TargetEmpty.
        /// </summary>
        public static string Gui_Execution_TargetEmpty {
            get {
                return ResourceManager.GetString("Gui_Execution_TargetEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_TargetFormat.
        /// </summary>
        public static string Gui_Execution_TargetFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TargetFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_TotalFilesFormat.
        /// </summary>
        public static string Gui_Execution_TotalFilesFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TotalFilesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Execution_TypeFormat.
        /// </summary>
        public static string Gui_Execution_TypeFormat {
            get {
                return ResourceManager.GetString("Gui_Execution_TypeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_ActiveJob.
        /// </summary>
        public static string Gui_JobEditor_ActiveJob {
            get {
                return ResourceManager.GetString("Gui_JobEditor_ActiveJob", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_ActiveJob_Hint.
        /// </summary>
        public static string Gui_JobEditor_ActiveJob_Hint {
            get {
                return ResourceManager.GetString("Gui_JobEditor_ActiveJob_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_BackupTypeHelp.
        /// </summary>
        public static string Gui_JobEditor_BackupTypeHelp {
            get {
                return ResourceManager.GetString("Gui_JobEditor_BackupTypeHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_BackupTypeLabel.
        /// </summary>
        public static string Gui_JobEditor_BackupTypeLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_BackupTypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_CreateButton.
        /// </summary>
        public static string Gui_JobEditor_CreateButton {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_CreatedFormat.
        /// </summary>
        public static string Gui_JobEditor_CreatedFormat {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreatedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_CreateSubtitle.
        /// </summary>
        public static string Gui_JobEditor_CreateSubtitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_CreateTitle.
        /// </summary>
        public static string Gui_JobEditor_CreateTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_CreateTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_EditSubtitle.
        /// </summary>
        public static string Gui_JobEditor_EditSubtitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_EditSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_EditTitle.
        /// </summary>
        public static string Gui_JobEditor_EditTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_EditTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_Error_NameLength.
        /// </summary>
        public static string Gui_JobEditor_Error_NameLength {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_NameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_Error_NameRequired.
        /// </summary>
        public static string Gui_JobEditor_Error_NameRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_Error_SourceRequired.
        /// </summary>
        public static string Gui_JobEditor_Error_SourceRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_SourceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_Error_TargetRequired.
        /// </summary>
        public static string Gui_JobEditor_Error_TargetRequired {
            get {
                return ResourceManager.GetString("Gui_JobEditor_Error_TargetRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_InfoTitle.
        /// </summary>
        public static string Gui_JobEditor_InfoTitle {
            get {
                return ResourceManager.GetString("Gui_JobEditor_InfoTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_LastRunFormat.
        /// </summary>
        public static string Gui_JobEditor_LastRunFormat {
            get {
                return ResourceManager.GetString("Gui_JobEditor_LastRunFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_LastRunNever.
        /// </summary>
        public static string Gui_JobEditor_LastRunNever {
            get {
                return ResourceManager.GetString("Gui_JobEditor_LastRunNever", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_NameLabel.
        /// </summary>
        public static string Gui_JobEditor_NameLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_NameWatermark.
        /// </summary>
        public static string Gui_JobEditor_NameWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_NameWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_RequiredFields.
        /// </summary>
        public static string Gui_JobEditor_RequiredFields {
            get {
                return ResourceManager.GetString("Gui_JobEditor_RequiredFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_SaveChanges.
        /// </summary>
        public static string Gui_JobEditor_SaveChanges {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SaveChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_SourceLabel.
        /// </summary>
        public static string Gui_JobEditor_SourceLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SourceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_SourceWatermark.
        /// </summary>
        public static string Gui_JobEditor_SourceWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_SourceWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_TargetLabel.
        /// </summary>
        public static string Gui_JobEditor_TargetLabel {
            get {
                return ResourceManager.GetString("Gui_JobEditor_TargetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobEditor_TargetWatermark.
        /// </summary>
        public static string Gui_JobEditor_TargetWatermark {
            get {
                return ResourceManager.GetString("Gui_JobEditor_TargetWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Active.
        /// </summary>
        public static string Gui_Jobs_Active {
            get {
                return ResourceManager.GetString("Gui_Jobs_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_ActiveJobsFormat.
        /// </summary>
        public static string Gui_Jobs_ActiveJobsFormat {
            get {
                return ResourceManager.GetString("Gui_Jobs_ActiveJobsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_CreateFirst.
        /// </summary>
        public static string Gui_Jobs_CreateFirst {
            get {
                return ResourceManager.GetString("Gui_Jobs_CreateFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Delete.
        /// </summary>
        public static string Gui_Jobs_Delete {
            get {
                return ResourceManager.GetString("Gui_Jobs_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_DeleteTooltip.
        /// </summary>
        public static string Gui_Jobs_DeleteTooltip {
            get {
                return ResourceManager.GetString("Gui_Jobs_DeleteTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Edit.
        /// </summary>
        public static string Gui_Jobs_Edit {
            get {
                return ResourceManager.GetString("Gui_Jobs_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_EditTooltip.
        /// </summary>
        public static string Gui_Jobs_EditTooltip {
            get {
                return ResourceManager.GetString("Gui_Jobs_EditTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Inactive.
        /// </summary>
        public static string Gui_Jobs_Inactive {
            get {
                return ResourceManager.GetString("Gui_Jobs_Inactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Label_Source.
        /// </summary>
        public static string Gui_Jobs_Label_Source {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Source", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Label_Target.
        /// </summary>
        public static string Gui_Jobs_Label_Target {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Target", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_Label_Type.
        /// </summary>
        public static string Gui_Jobs_Label_Type {
            get {
                return ResourceManager.GetString("Gui_Jobs_Label_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_LastRunFormat.
        /// </summary>
        public static string Gui_Jobs_LastRunFormat {
            get {
                return ResourceManager.GetString("Gui_Jobs_LastRunFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_LastRunNever.
        /// </summary>
        public static string Gui_Jobs_LastRunNever {
            get {
                return ResourceManager.GetString("Gui_Jobs_LastRunNever", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_New.
        /// </summary>
        public static string Gui_Jobs_New {
            get {
                return ResourceManager.GetString("Gui_Jobs_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_NoJobs_Hint.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Hint {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_NoJobs_Subtitle.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Subtitle {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Jobs_NoJobs_Title.
        /// </summary>
        public static string Gui_Jobs_NoJobs_Title {
            get {
                return ResourceManager.GetString("Gui_Jobs_NoJobs_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobStatus_Completed.
        /// </summary>
        public static string Gui_JobStatus_Completed {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobStatus_Error.
        /// </summary>
        public static string Gui_JobStatus_Error {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobStatus_Idle.
        /// </summary>
        public static string Gui_JobStatus_Idle {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Idle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobStatus_Paused.
        /// </summary>
        public static string Gui_JobStatus_Paused {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_JobStatus_Running.
        /// </summary>
        public static string Gui_JobStatus_Running {
            get {
                return ResourceManager.GetString("Gui_JobStatus_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_LogFormat_Json.
        /// </summary>
        public static string Gui_LogFormat_Json {
            get {
                return ResourceManager.GetString("Gui_LogFormat_Json", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_LogFormat_Xml.
        /// </summary>
        public static string Gui_LogFormat_Xml {
            get {
                return ResourceManager.GetString("Gui_LogFormat_Xml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_About.
        /// </summary>
        public static string Gui_Nav_About {
            get {
                return ResourceManager.GetString("Gui_Nav_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_BackupJobs.
        /// </summary>
        public static string Gui_Nav_BackupJobs {
            get {
                return ResourceManager.GetString("Gui_Nav_BackupJobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_Dashboard.
        /// </summary>
        public static string Gui_Nav_Dashboard {
            get {
                return ResourceManager.GetString("Gui_Nav_Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_LiveExecution.
        /// </summary>
        public static string Gui_Nav_LiveExecution {
            get {
                return ResourceManager.GetString("Gui_Nav_LiveExecution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_Logs.
        /// </summary>
        public static string Gui_Nav_Logs {
            get {
                return ResourceManager.GetString("Gui_Nav_Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Nav_Settings.
        /// </summary>
        public static string Gui_Nav_Settings {
            get {
                return ResourceManager.GetString("Gui_Nav_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_BusinessProcessLabel.
        /// </summary>
        public static string Gui_Settings_BusinessProcessLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_BusinessProcessTooltip.
        /// </summary>
        public static string Gui_Settings_BusinessProcessTooltip {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_BusinessProcessWatermark.
        /// </summary>
        public static string Gui_Settings_BusinessProcessWatermark {
            get {
                return ResourceManager.GetString("Gui_Settings_BusinessProcessWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_EnableXor.
        /// </summary>
        public static string Gui_Settings_EnableXor {
            get {
                return ResourceManager.GetString("Gui_Settings_EnableXor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_ExtensionsLabel.
        /// </summary>
        public static string Gui_Settings_ExtensionsLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_ExtensionsNote.
        /// </summary>
        public static string Gui_Settings_ExtensionsNote {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_ExtensionsTooltip.
        /// </summary>
        public static string Gui_Settings_ExtensionsTooltip {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_ExtensionsWatermark.
        /// </summary>
        public static string Gui_Settings_ExtensionsWatermark {
            get {
                return ResourceManager.GetString("Gui_Settings_ExtensionsWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_Info.
        /// </summary>
        public static string Gui_Settings_Info {
            get {
                return ResourceManager.GetString("Gui_Settings_Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_LanguageLabel.
        /// </summary>
        public static string Gui_Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_LanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_LogFormatLabel.
        /// </summary>
        public static string Gui_Settings_LogFormatLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_LogFormatLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_SecretKeyLabel.
        /// </summary>
        public static string Gui_Settings_SecretKeyLabel {
            get {
                return ResourceManager.GetString("Gui_Settings_SecretKeyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Settings_Title.
        /// </summary>
        public static string Gui_Settings_Title {
            get {
                return ResourceManager.GetString("Gui_Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Sidebar_System.
        /// </summary>
        public static string Gui_Sidebar_System {
            get {
                return ResourceManager.GetString("Gui_Sidebar_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Sidebar_Workspace.
        /// </summary>
        public static string Gui_Sidebar_Workspace {
            get {
                return ResourceManager.GetString("Gui_Sidebar_Workspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_AboutInfo.
        /// </summary>
        public static string Gui_Status_AboutInfo {
            get {
                return ResourceManager.GetString("Gui_Status_AboutInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_JobFormat.
        /// </summary>
        public static string Gui_Status_JobFormat {
            get {
                return ResourceManager.GetString("Gui_Status_JobFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_LiveMonitoring.
        /// </summary>
        public static string Gui_Status_LiveMonitoring {
            get {
                return ResourceManager.GetString("Gui_Status_LiveMonitoring", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_ManageJobs.
        /// </summary>
        public static string Gui_Status_ManageJobs {
            get {
                return ResourceManager.GetString("Gui_Status_ManageJobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_Overview.
        /// </summary>
        public static string Gui_Status_Overview {
            get {
                return ResourceManager.GetString("Gui_Status_Overview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_Ready.
        /// </summary>
        public static string Gui_Status_Ready {
            get {
                return ResourceManager.GetString("Gui_Status_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_SettingsInfo.
        /// </summary>
        public static string Gui_Status_SettingsInfo {
            get {
                return ResourceManager.GetString("Gui_Status_SettingsInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gui_Status_ViewLogs.
        /// </summary>
        public static string Gui_Status_ViewLogs {
            get {
                return ResourceManager.GetString("Gui_Status_ViewLogs", resourceCulture);
            }
        }


    }
}

